### ISSUE TITLE
[REQ] Improvements to C4 autoplant

### ISSUE THREAD

**Issue by crashzk** [LordFetznschaedl/CS2Retake#10]
From what I saw, it is already in the project to be improved. In this case, it would be an automatic autoplant, where the TR that was born with the C4 in the plant, when the freezetime ends, plants the C4 automatically, without the player needing to plant it in this case.

I don't know if it helps, but there would be this plugin for SourceMod with this function: https://github.com/B3none/retakes-autoplant/blob/master/addons/sourcemod/scripting/retakes_autoplant.sp

**Comment by LordFetznschaedl** [comment]
Hello @crashzk ,

Yes. My main goal currently is to get auto plant to work. I know this SM plugin and have tried to build it into CSS but the bomb is then not possible to be defused thus making it not playable.

The fastplant is only a current workaround.

Regards,
Robert

**Comment by LordFetznschaedl** [comment]
Thank you so much @Sonfloro ,

I wanted to implement it as well, sadly I had no time. I will take a look at your implementation and will add it to the plugin.

**Comment by LordFetznschaedl** [comment]
AutoPlant has now been added. It is used by default but can be changed to FastPlant in the Plugin Config (if anyone might prefer it to AutoPlant)
