### ISSUE TITLE
[BUG] Team balancing

### ISSUE THREAD

**Issue by crashzk** [LordFetznschaedl/CS2Retake#12]
Apparently the balancing system is not working, there are times when players are all on the same team, making it 5 vs 1 and the teams do not have automatic balancing.

Apparently there are no error logs on the server regarding the plugin, but it is attached.

[log-all20231124.txt](https://github.com/LordFetznschaedl/CS2Retake/files/13461984/log-all20231124.txt)
[log-cssharp20231124.txt](https://github.com/LordFetznschaedl/CS2Retake/files/13461985/log-cssharp20231124.txt)

**Comment by LordFetznschaedl** [comment]
Hello @crashzk ,

Thank you for logging the bug.
I will be taking a look at the balancing algorithm again.

Do you know by any chance if this happened after warmup, within the game, when someone joined,...?

Regarding the logs. CS2Retake does not currently use the new logging.

Thank you.

**Comment by crashzk** [comment]
Hi @LordFetznschaedl,

Firstly, thank you for your feedback.

About the bug, from what I noticed it always occurs during the game and when a player apparently chooses a team to join.

In my observations, I noticed that the player can choose the team he wants to play and join it and then after that the bug apparently occurs, apparently the team selection block is not fully working.

I believe that a solution to this would be to completely block the player from choosing the team option and always start as a Terrorist. And so make the plugin always leave 2 vs 1, that is, if 1 player enters the server, he plays TR, two players on the server, leaves one player on each side, 3 players on the server, leaves 2 TR and 1 CT . And so on, always leave a preference for TR of a maximum of 3 TR against 5 CT at the end.

I don't know if you can understand me, in any case I will get more information about the bug and when it occurs and how exactly and return with more information.

**Comment by LordFetznschaedl** [comment]
Hi.

The balancing will need further rework. In the future I have planned to add more configurability to the plugin.
Regarding the balancing. It should work (bugs exist that I have to solve) that the CTs are always in a advantageous situation if the player count on the server is uneven. 
If it is even the balancing will be equal (4v4 for example).

Just to confirm. You are using CS2Retake version 1.0.1-alpha or 1.0.2-alpha?

Thank you and regards, 
Robert

**Comment by crashzk** [comment]
> Hi.
> 
> The balancing will need further rework. In the future I have planned to add more configurability to the plugin. Regarding the balancing. It should work (bugs exist that I have to solve) that the CTs are always in a advantageous situation if the player count on the server is uneven. If it is even the balancing will be equal (4v4 for example).

I understand, I'll be waiting for updates then. I believe that the best thing is as mentioned, CT always has an advantage in player count.

> Just to confirm. You are using CS2Retake version 1.0.1-alpha or 1.0.2-alpha?
```
  [#3]: "CS2Retake" (1.0.2-alpha) by LordFetznschaedl
    Retake Plugin implementation for CS2
```

**Comment by crashzk** [comment]
More information I got about the bug. During the game itself, it occurs when someone connects to the server and chooses a team to join and then disconnects during the round. After that the balancer does not work correctly.

**Comment by LordFetznschaedl** [comment]
Queue System was reworked a couple of releases ago and works now properly. Teambalancing is now more configurable and works way better.
