### ISSUE TITLE
Wrong weapons for the type of round 

### ISSUE THREAD

**Issue by TomateCerise** [LordFetznschaedl/CS2Retake#19]
In "pistol" rounds we have riffles (full buy kit)

**Comment by LordFetznschaedl** [comment]
Hello @TomateCerise 

All available weapon kits currently have the RoundType "Undefined" which is a fallback if no weapon kit is configured for the specific roundtype. This was done to save on time while developing and most likely a better default config will be added in the future.

If you want to have weapon kits that are roundtype dependent you have the ability to edit this config.

Following RoundTypes are currently available:

Undefined (used as a fallback)
Pistol
Mid
FullBuy
I hope this helped

This was also discussed in issue #4.

Regards

**Comment by TomateCerise** [comment]
Thanks for the response ! 
And sorry for the duplicate

**Comment by LordFetznschaedl** [comment]
Hello @TomateCerise ,

no problem regarding the duplicated ticket. 
I will be closing this issue now.

I have just released a new version that has bug fixes and stability updates.

Regards, 
Robert
