### ISSUE TITLE
[BUG] Bombplant (terror team is freezing)

### ISSUE THREAD

**Issue by freakexeuLow** [LordFetznschaedl/CS2Retake#2]
Hey, first of all a big thank you for making it possible to bring Retake back to Cs2 :)

I noticed that as a terrorist if you don't place the bomb within the 5 seconds, you freeze and my mate was also affected (we both couldn't move anymore) this also applies after the 5 seconds if you still placed the bomb on the spot. Maybe there's no other way at the moment and we'll have to wait for some kind of autoplant like csgo had back then. 👍🏼

**Comment by LordFetznschaedl** [comment]
Hello and thank you.
I will have to test it again later with the newest CSS release.

Could you please check in the meantime that the offsets of CBasePlayerPawn_CommitSuicide is 356 for linux and windows.
You can check this in:
configs/addons/counterstrikesharp/gamedata/gamedata.json

Thank you.

**Comment by freakexeuLow** [comment]
> Hello and thank you. I will have to test it again later with the newest CSS release.
> 
> Could you please check in the meantime that the offsets of CBasePlayerPawn_CommitSuicide is 356 for linux and windows. You can check this in: configs/addons/counterstrikesharp/gamedata/gamedata.json
> 
> Thank you.

thanks for the answer and my css version is 54 
```
  "CBasePlayerPawn_CommitSuicide": {
    "offsets": {
      "windows": 355,
      "linux": 355
```

best regards

**Comment by LordFetznschaedl** [comment]
That will be the issue. You can just change those offsets to 356 and reboot your server. Then it should work. This was a bug in that API version.

I have forgotten to add the API Minimum Version.

Thank you.

**Comment by freakexeuLow** [comment]
> That will be the issue. You can just change those offsets to 356 and reboot your server. Then it should work. This was a bug in that API version.
> 
> I have forgotten to add the API Minimum Version.
> 
> Thank you.

this works now, but a new problem has arisen that they no longer all freeze but all die :D

**Comment by LordFetznschaedl** [comment]
The all T players die is wanted so that the round does not get prolonged by not planting. If the bomb is planted in time everything will be fine and the round can be played.

I am currently taking another look at having auto planting implemented so I can remove the feature :)

**Comment by freakexeuLow** [comment]
> The all T players die is wanted so that the round does not get prolonged by not planting. If the bomb is planted in time everything will be fine and the round can be played.
> 
> I am currently taking another look at having auto planting implemented so I can remove the feature :)

Hey and very sorry for the late reply, had had no internet for just under 3 days and okay. If you want, you can close the topic here. If there are any problems, I will come back to you 👍🏼

**Comment by LordFetznschaedl** [comment]
Thank you
