### ISSUE TITLE
round does not end when all dead

### ISSUE THREAD

**Issue by TheYukioSage** [LordFetznschaedl/CS2Retake#20]
I mean, when t-side has only 1 player, and he didn`t plant in time, he dies and ct player need to wait 40 seconds for round to restart. The same thing when t-player kills ct and he needs to wait for bomb to blow up. (sorry for my english)

**Comment by LordFetznschaedl** [comment]
Hello @TheYukioSage 

Have you replaced the gamedata.json after the last update? The last update has broken a lot of signatures.

If not. Please replace this json and retry.

Thank you.

**Comment by LordFetznschaedl** [comment]
Hello @TheYukioSage , 
I am guessing this was an issue with the signatures changing after one of the last cs updated. I will close this issue now.

Regards, 
Robert
