### ISSUE TITLE
Player Spawns are not working properly

### ISSUE THREAD

**Issue by Brazory** [LordFetznschaedl/CS2Retake#29]
Hello together!

The player spawns aren't working anymore for me. It could be an issue on my side, but as read in CSS Discord, i saw the issue probably:
_**"The fix for the Call To Arms update is RELEASED and it introduces a change to CCSPlayerController.Respawn  which swaps out the virtual function CCSPlayerPawn_Respawn for CBasePlayerController_SetPawn. This will guarantee that player pawns will be properly respawned."**_

Could this be the problem with the plugin? Or should i re-check my configs?

PS: Thank you for the CS2Retake Plugin!

Best regards!

**Comment by LordFetznschaedl** [comment]
Hi @Brazory 
Will be taking a look after work today. Thank you for the message.

**Comment by Brazory** [comment]
It was indeed just my own wrong config, after i had to reset the server. Spawns are working now, just autoplant not, but i guess thats a problem of my own config aswell. Will test and maybe give feedback if it wont work.
Thanks again!
