### ISSUE TITLE
Bomb planted - not disappearing from your "inventory"

### ISSUE THREAD

**Issue by Svampkant** [LordFetznschaedl/CS2Retake#7]
Trying out the plugin, when the bomb gets planted it isn't disappearing from the "planters" inventory.
Because of this you're not allowed to swap around any weapons.

Might be something to look in to =D

**Comment by LordFetznschaedl** [comment]
Hello @Svampkant, 

What gametype do you use? 
This plugin is currently verified to work with the competitive mode.

Have you copied all configs to the correct locations?

Thank you and regards, 
Robert

**Comment by Svampkant** [comment]
Thanks for such a fast reply.

That fixed the "issue" :P My bad, was casual. Now everything works as intended, cheers.

**Comment by LordFetznschaedl** [comment]
Thank you. I will close this issue and will open up an enhancement to try and get it working with casual aswell :)
